namespace SWTSharp.Events;

/// <summary>
/// Classes which implement this interface provide methods that deal with the events
/// that are generated by moving and resizing controls.
/// </summary>
public interface IControlListener
{
    /// <summary>
    /// Sent when the location (x, y) of a control changes relative to its parent
    /// (or relative to the display, for Shells).
    /// </summary>
    /// <param name="e">An event containing information about the move</param>
    void ControlMoved(ControlEvent e);

    /// <summary>
    /// Sent when the size (width, height) of a control changes.
    /// </summary>
    /// <param name="e">An event containing information about the resize</param>
    void ControlResized(ControlEvent e);
}

/// <summary>
/// This adapter class provides default implementations for the methods described by the
/// ControlListener interface.
/// </summary>
public abstract class ControlAdapter : IControlListener
{
    /// <summary>
    /// Sent when the location of a control changes.
    /// The default behavior is to do nothing.
    /// </summary>
    public virtual void ControlMoved(ControlEvent e) { }

    /// <summary>
    /// Sent when the size of a control changes.
    /// The default behavior is to do nothing.
    /// </summary>
    public virtual void ControlResized(ControlEvent e) { }
}
